GET http://localhost:4004/ HTTP/1.1
Accept: */*


GET http://localhost:4004/catalog HTTP/1.1
Authorization: Basic abd:


# create tenant t1
POST http://localhost:4004/-/cds/deployment/subscribe HTTP/1.1
Content-Type: application/json
Authorization: Basic eXZlczog

{ "tenant": "t1" }


# create tenant t2
POST http://localhost:4004/-/cds/deployment/subscribe HTTP/1.1
Content-Type: application/json
Authorization: Basic eXZlczog

{ "tenant": "t2" }


# unsubscribe tenant t1
POST http://localhost:4004/-/cds/deployment/unsubscribe HTTP/1.1
Content-Type: application/json
Authorization: Basic eXZlczog

{ "tenant": "t1" }


GET http://localhost:4004/catalog HTTP/1.1
Authorization: Basic yves:


